config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts, only: [:show]

  root 'posts#infinite_scrolling'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  PER_PAGE = 12
  before_action :load_query, only: :infinite_scrolling

  def infinite_scrolling
    respond_to do |format|
      format.html
      format.js do
        @pagination = @query_result['pagination']
      end
    end
  end

  def show; end

  private

  def load_query
    @query_result = VideoQuery.fetch(page: params[:page], per_page: PER_PAGE)
    @posts = @query_result['response'].map { |e| VideoItem.new(e) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.slim
hr
footer
  .container
    p.pull-right Created by #{link_to 'ruubyy.github.io', 'http://ruubyy.github.io', target: '_blank'}

app/views/layouts/_header.html.slim
nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
        span.sr-only Toggle navigation

      = link_to 'Zype Videos', root_path, class: 'navbar-brand'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title ZypeExample
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  body
    = render 'layouts/header'

    .container
      = yield

    = link_to '#', class: "btn btn-primary back-to-top-button hidden" do
      span.glyphicon.glyphicon-chevron-up

    = render 'layouts/footer'

app/views/posts/_post.html.slim
= link_to post_path(id: post['_id']), { title: post['title'] } do
  h2 = post['title']

  = image_tag(post.thumbnail(240))

p = truncate(strip_tags(post['description']), length: 100)

p = link_to 'Read more.. ', post_path(id: post['_id']), {title: post['title']}

hr

app/views/posts/infinite_scrolling.html.slim
h1 Zype Videos

hr

#listing-infinite-scrolling
  = render partial: 'posts/post', collection: @posts

#paginate-infinite-scrolling data-page="1"
  = image_tag 'ajax-loader.gif', alt: 'Loading...', title: 'Loading...'

app/views/posts/infinite_scrolling.js.slim
| $('#listing-infinite-scrolling').append('#{j render(partial: 'posts/post', collection: @posts) }');
| $('#paginate-infinite-scrolling img').hide();

- if @pagination['next']
  | $('#paginate-infinite-scrolling').data('page', '#{@pagination['next']}')
- else
  | $(window).off('scroll');
  | $('#paginate-infinite-scrolling').remove();

app/views/posts/show.html.slim
div id="zype_#{params[:id]}"

script src="https://player.zype.com/embed/#{params[:id]}.js?autoplay=true&app_key=#{Rails.application.secrets.zype_app_key}"
  type="text/javascript"

p = link_to 'Back .. ', root_path